### ISSUE TITLE
Geoserver Letter Capitalizations

### ISSUE THREAD

**Issue by kjlippold** [BYU-Hydroinformatics/hydroviewer#1]
Line 201 and 202 of wms.js get the watershed and sub basin name from the dropdown text, and then change it to lowercase before constructing the ajax url on line 221. Since the Dominican Republic layers have uppercase letters in their names on GeoServer (as well as a few others it looks like), the ajax url won't work. I fixed it by removing .toLowerCase() on those two lines, but I don't know if there's a reason it's that way. Is there a way the app can construct this url differently?

Here's the relevant block of code with .toLowerCase() commented out.

<img width="1000" alt="screen shot 2018-03-19 at 12 03 36 pm" src="https://user-images.githubusercontent.com/27028728/37613427-9f50719e-2b6d-11e8-9f5d-4fc07fb1a812.png">

**Comment by msouff** [comment]
Yes. Layers have to be named in all lower case and they have to end in drainage_line (e.g. dominican_republic-national-drainage_line) following the SPT accepted style.
